### ISSUE TITLE
[ENHANCEMENT] Add a license

### ISSUE THREAD

**Issue by ElBe-Plaq** [Blazzycrafter/rEdgeDeflect#8]
Please add a code license to secure your work.

**Comment by ElBe-Plaq** [comment]
A good one is MIT or GPL-3.0.

**Comment by ElBe-Plaq** [comment]
@Blazzycrafter

**Comment by Blazzycrafter** [comment]
> @Blazzycrafter

on it

**Comment by ElBe-Plaq** [comment]
Decided to use MIT license.

**Comment by ElBe-Plaq** [comment]
Sadly I can't do this.

**Comment by Blazzycrafter** [comment]
DONE in [c9a0d3b](https://github.com/Blazzycrafter/rEdgeDeflect/commit/c9a0d3b704eefd80457eef69cab8df4333186df9)
